title: GoRyne's blog
email: korsogogii@kookmin.ac.kr
description: It's GoRyne's blog!
author: GoRyne
#baseurl: ""
url: "https://goryne.github.io/"

# Social Profiles
twitter_username:
github_username: GoRyne
facebook_username:
instagram_username: 1in_a_hundred
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics: G-CCDHNBS6PC # out your google-analytics code

comment:
  provider: "disqus"
  disqus::
    shortname: "GoRyne"

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
